### ISSUE TITLE
VERSION.txt file not found

### ISSUE THREAD

**Issue by Michael-Getz** [tjsego/libSSR#1]
When attempting to use `pip install git+https://github.com/tjsego/libSSR@port#subdirectory=src/python` on Windows 11 I get the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-req-build-mp4eg29a\\src\\VERSION.txt'`
It seems that VERSION.txt is expected to be in the src folder, I can locally install the repo if I move the VERSION.txt file into the src folder without any issue.

**Comment by tjsego** [comment]
Thanks for reporting. Should be fixed by https://github.com/tjsego/libSSR/commit/587b0b8ac9967257661a660d917d05c4e3958799.

**Comment by tjsego** [comment]
@Michael-Getz can you confirm that this is resolved?

**Comment by Michael-Getz** [comment]
This issue was resolved.
